deploy 1

diff --git a/.github/workflows/astro.yml b/.github/workflows/astro.yml
--- a/.github/workflows/astro.yml
+++ b/.github/workflows/astro.yml
@@ -12,7 +12,32 @@ jobs:
       contents: read
       id-token: write
     steps:
+    - name: Checkout
     - uses: actions/checkout@v4
+
+    - name: Detect package manager
+      id: detect-package-manager
+      run: |
+        if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+          echo "manager=yarn" >> $GITHUB_OUTPUT
+          echo "command=install" >> $GITHUB_OUTPUT
+          echo "runner=yarn" >> $GITHUB_OUTPUT
+          echo "lockfile=yarn.lock" >> $GITHUB_OUTPUT
+          exit 0
+        elif [ -f "${{ github.workspace }}/package.json" ]; then
+          echo "manager=npm" >> $GITHUB_OUTPUT
+          echo "command=ci" >> $GITHUB_OUTPUT
+          echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+          echo "lockfile=package-lock.json" >> $GITHUB_OUTPUT
+          exit 0
+        else
+          echo "Unable to determine package manager"
+          exit 1
+        fi
+
+    - run: echo "1${{ steps.detect-package-manager.outputs.manager }}"
+    - run: echo "1${{ steps.detect-package-manager.outputs.command }}"
+    - run: echo "1${{ steps.detect-package-manager.outputs.runner }}"
 
     - name: Enable Corepack
       run: corepack enable
@@ -23,17 +48,25 @@ jobs:
         node-version: 22
         cache: 'npm'
 
+    - name: Setup Pages
+      id: pages
+      uses: actions/configure-pages@v5
+
+    - run: echo "1${{ steps.pages.outputs.origin }}"
+    - run: echo "1${{ steps.pages.outputs.base_path }}"
+    - run: echo "1${{ env.BUILD_PATH }}"
+
     - name: Install dependencies
-      run: npm install
+      run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      working-directory: ${{ env.BUILD_PATH }}
 
     - name: Ensure NuxtHub module is installed
       run: npx nuxthub@latest ensure
+    # - name: Build application
+    #   run: npm run build
 
-    - name: Build application
-      run: npm run build
-
-    - name: Deploy to NuxtHub
-      uses: nuxt-hub/action@v1
-      id: deploy
-      with:
-        project-key: fb-landing-kbyn
+    # - name: Deploy to NuxtHub
+    #   uses: nuxt-hub/action@v1
+    #   id: deploy
+    #   with:
+    #     project-key: fb-landing-kbyn
